name: Build and Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Test InferX
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH for private repositories
      if: env.SSH_PRIVATE_KEY != ''
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Warning - SSH Key Not Configured
      if: env.SSH_PRIVATE_KEY == ''
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "⚠️  WARNING: SSH_PRIVATE_KEY secret is not configured!"
        echo "📖 This project uses SSH URLs for Swift Package dependencies."
        echo "🔧 To fix this, see: .github/SSH_SETUP.md"
        echo ""
        echo "Quick setup:"
        echo "1. Generate SSH key: ssh-keygen -t ed25519 -C 'github-actions@inferx' -f ~/.ssh/id_ed25519_github_actions"
        echo "2. Add public key to: https://github.com/settings/keys"
        echo "3. Add private key to: https://github.com/${{ github.repository }}/settings/secrets/actions"
        echo "   Secret name: SSH_PRIVATE_KEY"
        echo ""
        echo "⚠️  Build may fail due to missing SSH access to dependencies!"

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Show available schemes
      run: xcodebuild -list -project InferX.xcodeproj

    - name: Resolve Package Dependencies
      run: |
        xcodebuild -resolvePackageDependencies \
          -project InferX.xcodeproj \
          -scheme InferX

    - name: Build project (skip clean to avoid macro issues)
      run: |
        xcodebuild build \
          -project InferX.xcodeproj \
          -scheme InferX \
          -destination 'generic/platform=macOS' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -skipMacroValidation \
          -skipPackagePluginValidation

    - name: Run tests
      run: |
        xcodebuild test \
          -project InferX.xcodeproj \
          -scheme InferX \
          -destination 'platform=macOS,name=Any Mac' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -skipMacroValidation \
          -skipPackagePluginValidation
      continue-on-error: true

    - name: Archive build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ~/Library/Logs/DiagnosticReports/
          *.log
        retention-days: 7
